// <auto-generated />
using CivilWar.Infra.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CivilWar.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230515190212_Migration1")]
    partial class Migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CivilWar.Infra.Model.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtackPower")
                        .HasColumnType("int");

                    b.Property<int>("DefensePower")
                        .HasColumnType("int");

                    b.Property<bool>("FavorRegisteringSuperhumans")
                        .HasColumnType("bit");

                    b.Property<int>("HealthPoint")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Heros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtackPower = 83,
                            DefensePower = 88,
                            FavorRegisteringSuperhumans = false,
                            HealthPoint = 500,
                            Name = "Capitão América"
                        },
                        new
                        {
                            Id = 2,
                            AtackPower = 75,
                            DefensePower = 100,
                            FavorRegisteringSuperhumans = false,
                            HealthPoint = 500,
                            Name = "Soldado Invernal"
                        },
                        new
                        {
                            Id = 3,
                            AtackPower = 88,
                            DefensePower = 77,
                            FavorRegisteringSuperhumans = false,
                            HealthPoint = 500,
                            Name = "Gavião Arqueiro"
                        },
                        new
                        {
                            Id = 4,
                            AtackPower = 93,
                            DefensePower = 77,
                            FavorRegisteringSuperhumans = false,
                            HealthPoint = 500,
                            Name = "Feiticeira Escarlate"
                        },
                        new
                        {
                            Id = 5,
                            AtackPower = 80,
                            DefensePower = 82,
                            FavorRegisteringSuperhumans = false,
                            HealthPoint = 500,
                            Name = "Falcão"
                        },
                        new
                        {
                            Id = 6,
                            AtackPower = 100,
                            DefensePower = 70,
                            FavorRegisteringSuperhumans = false,
                            HealthPoint = 500,
                            Name = "Hulk"
                        },
                        new
                        {
                            Id = 7,
                            AtackPower = 75,
                            DefensePower = 100,
                            FavorRegisteringSuperhumans = true,
                            HealthPoint = 500,
                            Name = "Homem de Ferro"
                        },
                        new
                        {
                            Id = 8,
                            AtackPower = 86,
                            DefensePower = 93,
                            FavorRegisteringSuperhumans = true,
                            HealthPoint = 500,
                            Name = "Pantera Negra"
                        },
                        new
                        {
                            Id = 9,
                            AtackPower = 88,
                            DefensePower = 77,
                            FavorRegisteringSuperhumans = true,
                            HealthPoint = 500,
                            Name = "Viúva Negra"
                        },
                        new
                        {
                            Id = 10,
                            AtackPower = 100,
                            DefensePower = 70,
                            FavorRegisteringSuperhumans = true,
                            HealthPoint = 500,
                            Name = "Visão"
                        },
                        new
                        {
                            Id = 11,
                            AtackPower = 75,
                            DefensePower = 100,
                            FavorRegisteringSuperhumans = true,
                            HealthPoint = 500,
                            Name = "Máquina de Combate"
                        },
                        new
                        {
                            Id = 12,
                            AtackPower = 80,
                            DefensePower = 82,
                            FavorRegisteringSuperhumans = true,
                            HealthPoint = 500,
                            Name = "Homem-Aranha"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
